### ISSUE TITLE
implementation 'com.github.jeancsanchez:JcPlayer:2.7.1'

### ISSUE THREAD

**Issue by chykennoch1** [jeancsanchez/JCPlayer#130]
hI,
After installing the dependency it come with below error message. Failed to resolve: com.github.jeancsanchez:JcPlayer:2.7.1

**Comment by shravz7** [comment]
hI,
After installing the dependency it come with below error message. Failed to resolve: com.github.jeancsanchez:JcPlayer:2.7.1

**Comment by jeancsanchez** [comment]
Try using version 2.7.2 and tell me if it worked.

**Comment by cabernabe** [comment]
hI,
After installing the dependency it comes with the below error message. Failed to resolve: com.github.jeancsanchez:JcPlayer:2.7.2

**Comment by avidtrakintegrations** [comment]
Same error. Can anybody help?
After installing the dependency it comes with the below error message. Failed to resolve: com.github.jeancsanchez:JcPlayer:2.7.2

**Comment by washingtonmaza** [comment]
Good afternoon, after the update I am also having a problem with version 2.7.2, would it be possible to fix it?

**Comment by jeancsanchez** [comment]
Let me see...

**Comment by jeancsanchez** [comment]
@cabernabe @avidtrakintegrations @washingtonmaza 
Ok, guys. I tried importing this library with an empty project and everything seems to work normally.
Did you follow all steps listed in the Readme file? Could you let me know if you added gradle dependencies to the project and application levels?

**Comment by washingtonmaza** [comment]
Sorry for not replying sooner, and thanks for the feedback!
 
 



De: "Em leons" ***@***.***>
Enviada: 2023/02/13 20:14:50
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [jeancsanchez/JcPlayer] implementation 'com.github.jeancsanchez:JcPlayer:2.7.1' (Issue #130)
 

 

@cabernabe add git pack url to your graddle

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/jeancsanchez/JcPlayer/issues/130#issuecomment-1428842221", "url": "https://github.com/jeancsanchez/JcPlayer/issues/130#issuecomment-1428842221", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by arpitamoharir** [comment]
hI,
After installing the dependency it comes with the below error message. Failed to resolve: com.github.jeancsanchez:JcPlayer:2.7.2

**Comment by washingtonmaza** [comment]
thanks for the update note, it will help a lot!



De: "Arpita Moharir" ***@***.***>
Enviada: 2023/04/28 03:14:19
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [jeancsanchez/JcPlayer] implementation 'com.github.jeancsanchez:JcPlayer:2.7.1' (Issue #130)
 

 

hI,
After installing the dependency it comes with the below error message. Failed to resolve: com.github.jeancsanchez:JcPlayer:2.7.2

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/jeancsanchez/JcPlayer/issues/130#issuecomment-1527042514", "url": "https://github.com/jeancsanchez/JcPlayer/issues/130#issuecomment-1527042514", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
